# Database credentials
database:
  file: "" 
  sql-user: "root"
  sql-pass: "password123"
  sql-server: "127.0.0.1" # Use localhost or 127.0.0.1 for local MySQL
  sql-database: "SupportSystem"
  sql-port: 3306

redis:
  server: "localhost:6379"

sso:
  clientId:  "StudentPortal"
  clientSecret:  "EM4WKTSRUXVWG5RBTXC3VPOBTMF5Y3SL"
  baseAddress:  "https://localhost:44375/"
  backBaseAddress: "https://localhost:8080/"
