FROM python:3.13-slim

RUN apt-get update && \
    apt-get install -y curl unzip default-mysql-client && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.9.12.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    apt-get clean && rm -rf /var/lib/apt/lists/* awscliv2.zip aws

RUN aws --version

CMD ["bash"]
