apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-backup
  namespace: abelsspace
spec:
  schedule: "0 2 * * *" # Every day at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql-backup
            image: abdelilahachir/mysql-backup-awscli:latest
            env:
              - name: MYSQL_PWD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: password
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: b2-s3-secret
                    key: accessKeyId
              - name: AWS_DISABLE_SDK_CHECKSUM
                value: "1"
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: b2-s3-secret
                    key: secretAccessKey
              - name: B2_BUCKET
                value: AbdelilahBucket
              - name: B2_ENDPOINT
                value: https://s3.eu-central-003.backblazeb2.com  
            command:
              - /bin/sh
              - -c
              - |
                export BACKUP_FILE=/backup/backup-$(date +%F-%H-%M-%S).sql
                mysqldump -h mysql -u root SupportSystem > $BACKUP_FILE
                aws s3 cp $BACKUP_FILE s3://AbdelilahBucket/backup.sql --endpoint-url https://s3.eu-central-003.backblazeb2.com
                rm $BACKUP_FILE
            volumeMounts:
              - name: backup-storage
                mountPath: /backup
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: mysql-backup-pvc